build site:
  image: node:lts
  stage: build
  script:
    - npm install
    - REACT_APP_NODE_ENV="production" npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/ root@$DEPLOYMENT_SERVER_IP:/var/www/html/monitoring-dashboard
    # - ssh root@$DEPLOYMENT_SERVER_IP "cd /root/landingpage1; serve -s -l 5002 build/"
