stages:
  - install_dependencies
  - build
  - test
  - deliveryToStage

install_dependencies:
  image: node:latest
  stage: install_dependencies
  tags:
    - datochain
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm install
  only:
    changes:
      - package.json

build:
  stage: build
  image: docker:18.09.8-dind
  tags:
    - datochain
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  only:
    - "master"
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
      - apk add --no-cache curl
      - apk add --no-cache jq
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA} ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}"
  after_script:
    - "docker logout ${CI_REGISTRY}"

deliveryToStage:
  stage: deliveryToStage
  image: docker:latest
  tags:
    - datochain
  only:
    - "master"
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
      - apk add curl
      - apk add  jq
      - apk add  sed
      - apk add git
      - mkdir -p ~/.ssh
      - mv ${gitlab_key} ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - ssh-add ~/.ssh/id_rsa
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - sed -i -z -E "s/monitoring-dashboard:[^\\n]+\\n/monitoring-dashboard:${CI_COMMIT_SHORT_SHA}\\n/g" prod/deployment.yaml #For argo sync
    - git config --global user.name "nguyentienthao"
    - git config --global user.email "nguyentienthao96@gmail.com"
    - git add .
    - git commit -m "[skip ci] ${CI_COMMIT_MESSAGE}"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git branch
    - git remote -v 
    - git push origin HEAD:$CI_COMMIT_REF_NAME

  after_script:
    - "docker logout ${CI_REGISTRY}"
