apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-hosting-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:bkblockchain/bksupplychain/platform/monitoring-dashboard.git
    targetRevision: HEAD
    path: prod/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default